#!/usr/bin/env bun

import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"
import path from "path"
import fs from "fs"
import { $ } from "bun"
import { fileURLToPath } from "url"
import type { BunPlugin } from "bun"

/**
 * Fix for @protobufjs/inquire in compiled Bun binaries.
 *
 * protobufjs uses `eval("require")("fs")` to optionally load Node built-ins.
 * In compiled Bun binaries, `require` is a module-scoped variable injected by
 * the bundler — NOT a global. The `eval` executes in global scope where
 * `require` doesn't exist, causing `inquire("fs")` to return null. This breaks
 * `protoLoader.loadSync()` → `protobufjs Root.loadSync()` → `util.fs.readFileSync()`
 * with: "null is not an object (evaluating 'util.fs.readFileSync')".
 *
 * The fix replaces `@protobufjs/inquire` at build time with a version that uses
 * a direct `require()` call (visible to the bundler) instead of `eval`.
 */
const inquireFixPlugin: BunPlugin = {
  name: "fix-protobufjs-inquire",
  setup(build) {
    build.onLoad({ filter: /\/@protobufjs\/inquire\/index\.js$/ }, () => ({
      contents: `"use strict";
module.exports = function inquire(moduleName) {
  try {
    var mod = require(moduleName);
    if (mod && (mod.length || Object.keys(mod).length))
      return mod;
  } catch (e) {}
  return null;
};`,
      loader: "js",
    }))
  },
}

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@opencode-ai/script"
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Generate proto-snapshot.ts from .proto files for compiled binary support.
// In compiled binaries, proto files can't be read from disk (they're not embedded
// in bunfs). We pre-compile them to a JSON descriptor and load via fromJSON().
const protosDir = path.resolve(dir, "../legion-client/protos")
const protoFileNames = [
  "auth.proto",
  "agent_skill.proto",
  "engagement.proto",
  "task.proto",
  "knowledge.proto",
  "expertise.proto",
  "memory.proto",
  "delegation.proto",
  "code.proto",
  "lessons_learned.proto",
  "legion_common.proto",
  "ingestion.proto",
  "proxy.proto",
  "session.proto",
  "conversation_extraction.proto",
  "unified_search.proto",
]
{
  const Protobuf = await import("protobufjs")
  const root = new Protobuf.default.Root()
  root.resolvePath = (_origin: string, target: string) => {
    if (path.isAbsolute(target)) return target
    return path.join(protosDir, target)
  }
  for (const f of protoFileNames) {
    const content = await Bun.file(path.join(protosDir, f)).text()
    Protobuf.default.parse(content, root, { keepCase: true })
  }
  root.resolveAll()
  const json = JSON.stringify(root.toJSON())
  await Bun.write(
    path.join(dir, "src/legion/proto-snapshot.ts"),
    `// Auto-generated by build.ts - do not edit\nexport const protoJSON = ${json} as const\n`,
  )
  console.log("Generated proto-snapshot.ts")
}

// Load migrations from migration directories
const migrationDirs = (await fs.promises.readdir(path.join(dir, "migration"), { withFileTypes: true }))
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

// --legion-default-host=<host> sets the compile-time default for gRPC connections.
// Production builds (via build-pkg.ts) pass api.wearethelegion.com.
// Local dev builds default to localhost.
const legionDefaultHost = (() => {
  const prefix = "--legion-default-host="
  const match = process.argv.find((a) => a.startsWith(prefix))
  return match ? match.slice(prefix.length) : "api.wearethelegion.com"
})()

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin, inquireFixPlugin],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      //@ts-ignore (bun types aren't up to date)
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/legion`,
      execArgv: [`--user-agent=legion/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OPENCODE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      LEGION_DEFAULT_HOST: `'${legionDefaultHost}'`,
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber`
}

export { binaries }
