/**
 * LEGION Authentication & Token Management (F-003)
 *
 * Manages the LegionClient singleton: authenticates on startup,
 * caches the authenticated client, and provides graceful fallback
 * when LEGION is not configured or unreachable.
 *
 * Credentials are persisted to disk after successful login so
 * subsequent sessions re-authenticate automatically.
 */

import path from "path"
import fs from "fs/promises"
import { LegionClient, LegionConnectionError } from "@opencode-ai/legion-client"
import { Log } from "../util/log"
import { Global } from "../global"

// Pre-compiled proto JSON for compiled binaries (generated by build.ts).
// Falls back to null when running from source (proto files loaded from disk).
let protoJSON: Record<string, any> | null = null
try {
  const snapshot = require("./proto-snapshot")
  protoJSON = snapshot.protoJSON ?? null
} catch {
  // Running from source — LegionClient will load .proto files from disk
}

const log = Log.create({ service: "legion.auth" })

// ---------------------------------------------------------------------------
// Singleton state
// ---------------------------------------------------------------------------

let clientInstance: LegionClient | null = null
let authPromise: Promise<LegionClient | null> | null = null

// ---------------------------------------------------------------------------
// Credential persistence
// ---------------------------------------------------------------------------

const CREDS_FILE = path.join(Global.Path.legion, "legion-auth.json")

interface SavedCredentials {
  email?: string
  password?: string
  serverUrl?: string
  apiKey?: string
}

// ---------------------------------------------------------------------------
// In-memory session context (selected fresh every CLI launch)
// ---------------------------------------------------------------------------

let selectedCompanyId: string | null = null
let selectedProjectId: string | null = null

export function setLegionSession(companyId: string, projectId: string): void {
  selectedCompanyId = companyId
  selectedProjectId = projectId
}

export function getLegionCompanyId(): string | null {
  return selectedCompanyId
}

export function getLegionProjectId(): string | null {
  return selectedProjectId
}

async function saveCredentials(creds: SavedCredentials): Promise<void> {
  await fs.mkdir(Global.Path.legion, { recursive: true })
  await Bun.write(CREDS_FILE, JSON.stringify(creds, null, 2), { mode: 0o600 })
  log.info("LEGION credentials saved")
}

async function loadCredentials(): Promise<SavedCredentials | null> {
  const file = Bun.file(CREDS_FILE)
  if (!(await file.exists())) return null
  const data = await file.json().catch(() => null)
  if (!data || typeof data !== "object") return null
  return data as SavedCredentials
}

/**
 * Check whether stored credentials exist on disk.
 * Use this to decide whether to show the login page on startup.
 */
export async function hasLegionCredentials(): Promise<boolean> {
  const saved = await loadCredentials()
  if (saved?.apiKey) return true
  if (saved?.email && saved?.password) return true
  // Also check env vars
  if (process.env.LEGION_API_KEY) return true
  if (process.env.MCP_USER_EMAIL && process.env.MCP_USER_PASSWORD) return true
  return false
}

/**
 * Remove stored credentials (logout).
 */
export async function clearLegionCredentials(): Promise<void> {
  const fs = await import("fs/promises")
  await fs.unlink(CREDS_FILE).catch(() => {})
  log.info("LEGION credentials cleared")
}

// ---------------------------------------------------------------------------
// Config resolution
// ---------------------------------------------------------------------------

interface LegionConnectionConfig {
  host: string
  port: number
  apiKey?: string
  email?: string
  password?: string
}

/**
 * Resolve connection config from:
 * 1. Explicit config (login form values)
 * 2. Environment variables
 * 3. Saved credentials on disk
 *
 * Returns null if no credentials are available from any source.
 */
async function resolveConnectionConfig(legionConfig?: {
  serverUrl?: string
  email?: string
  password?: string
}): Promise<LegionConnectionConfig | null> {
  const saved = await loadCredentials()

  const host =
    process.env.GRPC_SERVER_HOST ?? extractHost(legionConfig?.serverUrl) ?? extractHost(saved?.serverUrl) ?? undefined
  const port =
    parseInt(process.env.GRPC_SERVER_PORT ?? "", 10) ||
    extractPort(legionConfig?.serverUrl) ||
    extractPort(saved?.serverUrl) ||
    undefined

  const apiKey = process.env.LEGION_API_KEY ?? saved?.apiKey ?? undefined
  const email = legionConfig?.email ?? process.env.MCP_USER_EMAIL ?? saved?.email ?? undefined
  const password = legionConfig?.password ?? process.env.MCP_USER_PASSWORD ?? saved?.password ?? undefined

  // Need at least credentials to be useful
  const hasCredentials = !!(apiKey || (email && password))
  if (!hasCredentials) return null

  return {
    host: host ?? "localhost",
    port: port ?? 50051,
    apiKey,
    email,
    password,
  }
}

function extractHost(serverUrl?: string): string | undefined {
  if (!serverUrl) return undefined
  try {
    // Handle "host:port" format (no protocol)
    const parts = serverUrl.split(":")
    return parts[0] || undefined
  } catch {
    return undefined
  }
}

function extractPort(serverUrl?: string): number | undefined {
  if (!serverUrl) return undefined
  try {
    const parts = serverUrl.split(":")
    if (parts.length >= 2) {
      const port = parseInt(parts[parts.length - 1], 10)
      return isNaN(port) ? undefined : port
    }
  } catch {
    // ignore
  }
  return undefined
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Authenticate with LEGION and return the client singleton.
 *
 * - First call creates and authenticates the client.
 * - Subsequent calls return the cached instance.
 * - If LEGION is not configured, returns null immediately.
 * - If authentication fails, logs warning and returns null (graceful degradation).
 */
export async function authenticateLegion(legionConfig?: {
  serverUrl?: string
  email?: string
  password?: string
}): Promise<LegionClient | null> {
  log.info("authenticateLegion called", {
    hasEmail: String(!!legionConfig?.email),
    hasPassword: String(!!legionConfig?.password),
    serverUrl: legionConfig?.serverUrl ?? "none",
    hasCachedClient: String(!!clientInstance),
    hasPendingPromise: String(!!authPromise),
  })

  const hasExplicitCreds = !!(legionConfig?.email && legionConfig?.password)

  if (!hasExplicitCreds) {
    if (clientInstance) {
      log.info("returning cached client")
      return clientInstance
    }
    if (authPromise) {
      log.info("returning pending auth promise")
      return authPromise
    }
  }

  if (hasExplicitCreds && clientInstance) {
    log.info("closing stale client for fresh auth")
    try {
      clientInstance.close()
    } catch {}
    clientInstance = null
  }

  log.info("starting fresh _doAuthenticate")
  authPromise = _doAuthenticate(legionConfig)
  try {
    return await authPromise
  } finally {
    authPromise = null
  }
}

async function _doAuthenticate(legionConfig?: {
  serverUrl?: string
  email?: string
  password?: string
}): Promise<LegionClient | null> {
  const connConfig = await resolveConnectionConfig(legionConfig)
  if (!connConfig) {
    log.info("LEGION not configured — skipping authentication")
    return null
  }

  log.info("_doAuthenticate: creating LegionClient", {
    host: connConfig.host,
    port: String(connConfig.port),
    method: connConfig.apiKey ? "api_key" : "email/password",
  })

  let client: LegionClient
  try {
    client = new LegionClient({
      host: connConfig.host,
      port: connConfig.port,
      apiKey: connConfig.apiKey,
      email: connConfig.email,
      password: connConfig.password,
      ...(protoJSON ? { protoJSON } : {}),
    })
    log.info("_doAuthenticate: LegionClient created OK")
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    log.error("_doAuthenticate: LegionClient constructor FAILED", { error: msg })
    throw new Error(`LegionClient constructor failed: ${msg}`)
  }

  try {
    log.info("_doAuthenticate: calling client.authenticate()...")
    await client.authenticate()
    log.info("_doAuthenticate: authenticated OK", { email: client.userEmail ?? "unknown" })
    clientInstance = client

    // Persist credentials so subsequent sessions re-authenticate automatically
    await saveCredentials({
      email: connConfig.email,
      password: connConfig.password,
      serverUrl:
        connConfig.host !== "localhost" || connConfig.port !== 50051
          ? `${connConfig.host}:${connConfig.port}`
          : undefined,
      apiKey: connConfig.apiKey,
    }).catch((err) =>
      log.warn("failed to save LEGION credentials", {
        error: err instanceof Error ? err.message : String(err),
      }),
    )

    return client
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    log.warn("LEGION authentication failed", { error: msg, host: connConfig.host, port: String(connConfig.port) })
    // Clean up the failed client
    try {
      client.close()
    } catch {
      // ignore
    }
    // Re-throw so callers (login form) can display the actual error
    throw new Error(`LEGION auth failed (${connConfig.host}:${connConfig.port}): ${msg}`)
  }
}

/**
 * Get the authenticated LegionClient singleton.
 * Returns null if LEGION is not configured or authentication failed.
 * Does NOT trigger authentication — call `authenticateLegion()` first.
 */
export function getLegionClient(): LegionClient | null {
  return clientInstance
}

/**
 * Check if LEGION is available (authenticated and ready).
 */
export function isLegionAvailable(): boolean {
  return clientInstance !== null
}

/**
 * Close the LEGION client and clear singleton state.
 * Call during shutdown or when reconfiguring.
 */
export function closeLegionClient(): void {
  if (clientInstance) {
    try {
      clientInstance.close()
    } catch {
      // ignore close errors
    }
    clientInstance = null
  }
}
